AWSTemplateFormatVersion: '2010-09-09'
Description: Stack independiente para el VPC Endpoint de SNS de Penguin On The Way!

Parameters:
  EnvironmentName:
    Type: String
    Description: Prefijo de los recursos
  PrivateAppSubnet1Id:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet privada de aplicacion AZ1
  PrivateAppSubnet2Id:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet privada de aplicacion AZ2

Resources:

  # VPC Endpoint Security Group

  VpcEndpointSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${EnvironmentName}-SNS-VPCE-SG"
      GroupDescription: "Permite trafico desde EC2 hacia el VPC Endpoint de SNS"
      VpcId: !ImportValue PenguinVpcId
      SecurityGroupIngress:
        - IpProtocol: -1
          SourceSecurityGroupId: !ImportValue POTW-EC2SecurityGroupId
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0

  # VPC Endpoint para SNS
  SnsVpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !ImportValue PenguinVpcId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.sns"
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref PrivateAppSubnet1Id
        - !Ref PrivateAppSubnet2Id
      SecurityGroupIds:
        - !Ref VpcEndpointSG
      PrivateDnsEnabled: true
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName} SNS VPC Endpoint"

Outputs:
  SnsVpcEndpointId:
    Description: ID del VPC Endpoint de SNS
    Value: !Ref SnsVpcEndpoint
    Export:
      Name: !Sub "${EnvironmentName}-SnsVpcEndpointId"

  VpcEndpointSGId:
    Description: Security Group asociado al VPC Endpoint
    Value: !Ref VpcEndpointSG
    Export:
      Name: !Sub "${EnvironmentName}-VpcEndpointSGId"